export * from "./Registration";
export * from "./Login";
export * from "./ForgotPassword";
export * from "./Profile";
// export * from "./AllTeamProject";
export * from "./Team";
export * from "./UserProjects";
export * from "./Modal";
export * from "./AddNewProject";
export * from "./Navbar";
export * from "./ChangePassword";
export * from "./SetNewPassword";
export * from "./ContactForm";
export * from "./InputDoubleClick";
